// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZvETUWiQz4oPLdWHpT8MNICdRFMRQj4',
    appId: '1:783435250588:android:1f58c84e8c137284d76659',
    messagingSenderId: '783435250588',
    projectId: 'account-app-d0bd7',
    storageBucket: 'account-app-d0bd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzs1VpTuTRXatu-dhl0L2lqUXRpWW2d8',
    appId: '1:783435250588:ios:2480877d67d68a50d76659',
    messagingSenderId: '783435250588',
    projectId: 'account-app-d0bd7',
    storageBucket: 'account-app-d0bd7.appspot.com',
    androidClientId: '783435250588-03i40mt1jkrr9qqvusvdg8249r93u255.apps.googleusercontent.com',
    iosClientId: '783435250588-13t61jjopn6rlnse210mu8fueav52d6g.apps.googleusercontent.com',
    iosBundleId: 'com.thanh.noteapp.noteApp',
  );
}
